//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;public partial class Shop {    protected global::System.Web.UI.WebControls.TextBox txtSearch;    protected global::System.Web.UI.WebControls.DropDownList ddlCategory;    protected global::System.Web.UI.WebControls.DropDownList ddlPriceRange;    protected global::System.Web.UI.WebControls.DropDownList ddlSortBy;    protected global::System.Web.UI.WebControls.Repeater rptProducts;    protected global::System.Web.UI.WebControls.Panel pnlNoResults;    protected global::System.Web.UI.WebControls.Label lblResultsCount;}